#!/usr/bin/env bash

# Binary base path
BASEDIR="/opt/steamos-session"

# Setup a steamdeck session
cp ${BASEDIR}/config/bash/.bash_profile.deckify ${HOME}/.bash_profile
if [[ -x "/usr/bin/plasmalogin" ]]; then
    sudo systemctl mask plasmalogin.service
    sudo systemctl unmask getty@tty1.service
    systemctl reboot
elif [[ -x "/usr/bin/gdm" ]]; then
    sudo systemctl mask gdm.service
    sudo systemctl unmask getty@tty1.service
    systemctl reboot
elif [[ -x "/usr/bin/lightdm" ]]; then
    sudo systemctl mask lightdm.service
    sudo systemctl unmask getty@tty1.service
    systemctl reboot
elif [[ -x "/usr/bin/sddm" ]]; then
    sudo systemctl mask sddm.service
    sudo systemctl unmask getty@tty1.service
    systemctl reboot
else
    echo -e "Display session manager not supported"
fi
