#!/usr/bin/env bash

# Type in your disred login manager
LOGIN_MANGER="plasmalogin"

# Define paths
GETTY_OVERRIDE_DIR="/etc/systemd/system/getty@tty6.service.d"
GETTY_OVERRIDE_FILE="$GETTY_OVERRIDE_DIR/override.conf"
SUDOERS_FILE="/etc/sudoers.d/steamos-session-overrides"
USER_SH_PROFILE="/home/$REAL_USER/.bash_profile"

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (sudo)."

   # Configure Getty Autologin
   mkdir -p "$GETTY_OVERRIDE_DIR"
   REAL_USER=${SUDO_USER:-$USER}

   cat <<EOF > "$GETTY_OVERRIDE_FILE"
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $REAL_USER --noclear %I 38400 linux
EOF

   echo "Getty override created for user: $REAL_USER"

   # This allows the performance and power scripts to run without password prompts
   cat <<EOF > "$SUDOERS_FILE"
# Nvidia specific power limits changes
%wheel ALL=(ALL) NOPASSWD: /usr/bin/nvidia-smi
%wheel ALL=(ALL) NOPASSWD: /usr/bin/nvidia-settings

# SteamOS Enhanced Gamemode
%wheel ALL=(ALL) NOPASSWD: /opt/steamos-session/steamos-gamemode-enhanced

# SteamOS TTY Handoff
%wheel ALL=(ALL) NOPASSWD: /opt/steamos-session/steamos-session-switcher

# Change Virtual Terminals (All 6 Supported Archlinux TTY Termianls)
%wheel ALL=(ALL) NOPASSWD: /usr/bin/chvt 6

# Start and Stop LightDM Display Manager
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl start lightdm.service
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop lightdm.service

# Start and Stop GDM Display Manager
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl start gdm.service
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop gdm.service

# Start and Stop Plasma Display Manager
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl start plasmalogin.service
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop plasmalogin.service

# Start and Stop SDDM Display Manager
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl start sddm.service
%wheel ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop sddm.service

# Force end the tty6 session
%wheel ALL=(ALL) NOPASSWD: /usr/bin/openvt *
EOF

   # Set correct permissions for sudoers file
   chmod 440 "$SUDOERS_FILE"
   echo "Sudoers overrides written to $SUDOERS_FILE"

   # Enable Getty TTY6 Autologin Service
   systemctl daemon-reload
   systemctl enable getty@tty6.service

   # Set GPU Priority CAP
   setcap 'cap_sys_nice=eip' $(which gamescope)

   # Create the bash profile for the session
   cp ".bash_profile" "$USER_SH_PROFILE"

   echo "Configuration complete. Getty autologin and sudoers permissions are active."
   exit 1

fi
