#!/bin/env bash

BASEDIR="/opt/steamos-session"

if [[ "$1" == "--deckify" ]]; then
	cp ${BASEDIR}/config/.bash_profile.deckify ${HOME}/.bash_profile
	if [[ -x "/usr/bin/plasmalogin" ]]; then
		sudo systemctl mask plasmalogin.service
		systemctl reboot
	elif [[ -x "/usr/bin/gdm" ]]; then
		sudo systemctl mask gdm.service
		systemctl reboot
	elif [[ -x "/usr/bin/lightdm" ]]; then
		sudo systemctl mask lightdm.service
		systemctl reboot
	elif [[ -x "/usr/bin/sddm" ]]; then
		sudo systemctl mask sddm.service
		systemctl reboot
	else
		echo -e "Display session manager not supported"
	fi
elif [[ "$1" == "--normal" ]]; then
	cp ${BASEDIR}/config/.bash_profile.normal ${HOME}/.bash_profile
	if [[ -x "/usr/bin/plasmalogin" ]]; then
		sudo systemctl unmask plasmalogin.service
		systemctl reboot
	elif [[ -x "/usr/bin/gdm" ]]; then
		sudo systemctl unmask gdm.service
		systemctl reboot
	elif [[ -x "/usr/bin/lightdm" ]]; then
		sudo systemctl unmask lightdm.service
		systemctl reboot
	elif [[ -x "/usr/bin/sddm" ]]; then
		sudo systemctl unmask sddm.service
		systemctl reboot
	else
		echo -e "Display session manager not supported"
	fi
elif [[ "$1" == "--help" ]]; then
	echo -e "SteamOS Deckify Toggle"
	echo -e ""
	echo -e "--deckify: Toggle the steamdeck console setup"
	echo -e "--normal: Toggle normal install without the gamemode console boot sequence"
	echo -e "--help: Show this help message"
else
	echo -e "Please type in a valid option, use --help for more details"
fi
