#!/usr/bin/env bash

# Identify the actual user to handle XDG_RUNTIME and PipeWire socket paths correctly when run as sudo
REAL_USER=${SUDO_USER:-$USER}

# The users home
BASEDIR="/home/$REAL_USER/.local/bin"

# The linking logic
SOURCE="$BASEDIR/steamos-session-select"
TARGET="/usr/bin/steamos-session-select"

# Apply changes
if ! cmp -s "$SOURCE" "$TARGET"; then
    echo "Updating steamos-session-select..."
    sudo ostree admin unlock
    sudo ln -sf "$SOURCE" "$TARGET"
    sudo ostree admin lock-finalization
else
    echo "steamos-session-select is already correctly configured."
fi
