#!/bin/env bash

BASEDIR="/opt/steamos-session"

if [[ "$1" == "--deckify" ]]; then
	cp ${BASEDIR}/config/.bash_profile.deckify ${HOME}/.bash_profile
	sudo systemctl mask display-manager.service
	sudo systemctl unmask getty@tty1.service
	systemctl reboot
elif [[ "$1" == "--normal" ]]; then
	cp ${BASEDIR}/config/.bash_profile.normal ${HOME}/.bash_profile
	sudo systemctl unmask display-manager.service
	sudo systemctl mask getty@tty1.service
	systemctl reboot
elif [[ "$1" == "--help" ]]; then
	echo -e "SteamOS Deckify Toggle"
	echo -e ""
	echo -e "--deckify: Toggle the steamdeck console setup"
	echo -e "--normal: Toggle normal install without the gamemode console boot sequence"
	echo -e "--help: Show this help message"
else
	echo -e "Please type in a valid option, use --help for more details"
fi
